name: recargas_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1  # Versión más reciente
  http: ^1.3.0  # Versión más reciente
  riverpod_annotation: ^2.6.1  # Versión más reciente
  sqflite: ^2.3.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  build_runner: # Versión más reciente
  custom_lint:
  riverpod_lint: ^2.6.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
